# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import CypherQuery_pb2 as CypherQuery__pb2


class CypherQueryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.queryCypher = channel.unary_unary(
                '/com.codenotfound.grpc.helloworld.CypherQueryService/queryCypher',
                request_serializer=CypherQuery__pb2.QueryMsg.SerializeToString,
                response_deserializer=CypherQuery__pb2.QueryResults.FromString,
                )


class CypherQueryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def queryCypher(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CypherQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'queryCypher': grpc.unary_unary_rpc_method_handler(
                    servicer.queryCypher,
                    request_deserializer=CypherQuery__pb2.QueryMsg.FromString,
                    response_serializer=CypherQuery__pb2.QueryResults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.codenotfound.grpc.helloworld.CypherQueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CypherQueryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def queryCypher(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.codenotfound.grpc.helloworld.CypherQueryService/queryCypher',
            CypherQuery__pb2.QueryMsg.SerializeToString,
            CypherQuery__pb2.QueryResults.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
