# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HelloWorld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10HelloWorld.proto\x12 com.codenotfound.grpc.helloworld\"/\n\x06Person\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\"\x1b\n\x08Greeting\x12\x0f\n\x07message\x18\x01 \x01(\t2u\n\x11HelloWorldService\x12`\n\x08sayHello\x12(.com.codenotfound.grpc.helloworld.Person\x1a*.com.codenotfound.grpc.helloworld.GreetingB\x02P\x01\x62\x06proto3')



_PERSON = DESCRIPTOR.message_types_by_name['Person']
_GREETING = DESCRIPTOR.message_types_by_name['Greeting']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'HelloWorld_pb2'
  # @@protoc_insertion_point(class_scope:com.codenotfound.grpc.helloworld.Person)
  })
_sym_db.RegisterMessage(Person)

Greeting = _reflection.GeneratedProtocolMessageType('Greeting', (_message.Message,), {
  'DESCRIPTOR' : _GREETING,
  '__module__' : 'HelloWorld_pb2'
  # @@protoc_insertion_point(class_scope:com.codenotfound.grpc.helloworld.Greeting)
  })
_sym_db.RegisterMessage(Greeting)

_HELLOWORLDSERVICE = DESCRIPTOR.services_by_name['HelloWorldService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _PERSON._serialized_start=54
  _PERSON._serialized_end=101
  _GREETING._serialized_start=103
  _GREETING._serialized_end=130
  _HELLOWORLDSERVICE._serialized_start=132
  _HELLOWORLDSERVICE._serialized_end=249
# @@protoc_insertion_point(module_scope)
